version: "3"
services:
  # Для запуска приложения запустите: docker-compose up web
  web:
    image: nginx:1.17-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/config/nginx.conf
      - ./:/code
    command: nginx -c /config/nginx.conf
    user: root
    ports:
      - "8081:8081"
    depends_on:
      - fpm
      - redis
      - mysql
    stop_signal: SIGTERM

  # Процесс fpm
  fpm:
    build: ./docker/php
    volumes:
      - ./:/code

  # Редис
  redis:
    image: "redis:6.0.2-alpine"

  mysql:
    image: "mysql:8.4.0"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: antispam
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    volumes:
      - antispam-db:/var/lib/mysql

  # Для запуска тестов запустите: docker-compose up tests
  tests:
    build: ./docker/php
    command: /usr/local/bin/codecept run -vvv
    volumes:
      - ./:/code
    depends_on:
      - web

  # Для запуска терминала с настроенной средой php запустите: docker-compose run terminal
  terminal:
    build: ./docker/php
    entrypoint: /bin/sh
    volumes:
      - ./:/code

volumes:
  antispam-db:
