controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#routes:
#    resource: "routes/routes.yaml"
#    type: "yaml"
#

#spam:
#    path: /is_spam
#    controller: App\Controller\SpamController::isSpam
#    methods: ['POST']

#invalidate_cache:
#    path: /invalidate_cache
#    controller: App\Controller\SpamController::invalidateCache
#    methods: ['POST']