controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

entity_list:
    path: /api/entities
    controller: App\Controller\EntityController::entityList